# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dev Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies 
      run: dotnet restore NoteBase/NoteBase.sln
    - name: Build
      run: dotnet build NoteBase/NoteBase.sln --no-restore
    - name: Test
      run: dotnet test NoteBase/NoteBase.sln
