name: Publish Docker Image to Docker Hub v2

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/notebase -f NoteBase/App/Dockerfile ./ --no-cache CLIENTID=${{ secrets.CLIENTID }} CLIENTSECRET=${{ secrets.CLIENTSECRET }} ASPNETCORE_ENVIRONMENT=Production

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notebase
