name: Main Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies 
      run: dotnet restore NoteBase/NoteBase.sln
    - name: Build
      run: dotnet build --configuration Release NoteBase/NoteBase.sln --no-restore
    - name: Test
      run: dotnet test NoteBase/NoteBase.sln
